language: c

arch:
  - amd64
  - ppc64le

addons:
  apt:
    packages:
    - libssl-dev
    - libcurl4-openssl-dev
    - libjansson-dev
    - libhiredis-dev
    - libpcre2-dev
    - apache2-dev
    - check

install:
  - wget https://github.com/cisco/cjose/archive/0.5.1.tar.gz
  - tar zxvf 0.5.1.tar.gz
  - cd cjose-0.5.1
  - ./configure --prefix=/usr
  - make test
  - sudo make install
  - cd -

before_script:
  - ./autogen.sh && ./configure

script:
  - make check
